$r = [char]0xFFFD
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)

$files = @(
    "modules\RH\public\pages\calendario-rh.html",
    "modules\RH\public\gestao-holerites.html"
)

foreach ($relPath in $files) {
    $f = Join-Path "g:\Outros computadores\Meu laptop (2)\Zyntra" $relPath
    if (-not (Test-Path $f)) { Write-Host "SKIP: $relPath (not found)"; continue }
    
    $c = [System.IO.File]::ReadAllText($f, [System.Text.Encoding]::UTF8)
    $before = ([regex]::Matches($c, [regex]::Escape([string]$r))).Count
    
    # Common Portuguese encoding fixes (longer patterns first)
    $c = $c.Replace("Marca${r}${r}es", "Marcações")
    $c = $c.Replace("marca${r}${r}es", "marcações")
    $c = $c.Replace("Marca${r}${r}o", "Marcação")
    $c = $c.Replace("marca${r}${r}o", "marcação")
    $c = $c.Replace("Observa${r}${r}o", "Observação")
    $c = $c.Replace("observa${r}${r}o", "observação")
    $c = $c.Replace("altera${r}${r}es", "alterações")
    $c = $c.Replace("altera${r}${r}o", "alteração")
    $c = $c.Replace("Altera${r}${r}es", "Alterações")
    $c = $c.Replace("Altera${r}${r}o", "Alteração")
    $c = $c.Replace("edi${r}${r}es", "edições")
    $c = $c.Replace("Edi${r}${r}o", "Edição")
    $c = $c.Replace("edi${r}${r}o", "edição")
    $c = $c.Replace("Cria${r}${r}o", "Criação")
    $c = $c.Replace("cria${r}${r}o", "criação")
    $c = $c.Replace("informa${r}${r}es", "informações")
    $c = $c.Replace("Informa${r}${r}es", "Informações")
    $c = $c.Replace("configura${r}${r}es", "configurações")
    $c = $c.Replace("Configura${r}${r}es", "Configurações")
    $c = $c.Replace("opera${r}${r}o", "operação")
    $c = $c.Replace("Opera${r}${r}o", "Operação")
    $c = $c.Replace("solicita${r}${r}o", "solicitação")
    $c = $c.Replace("Solicita${r}${r}o", "Solicitação")
    $c = $c.Replace("solicita${r}${r}es", "solicitações")
    $c = $c.Replace("Solicita${r}${r}es", "Solicitações")
    $c = $c.Replace("notifica${r}${r}o", "notificação")
    $c = $c.Replace("Notifica${r}${r}o", "Notificação")
    $c = $c.Replace("notifica${r}${r}es", "notificações")
    $c = $c.Replace("Notifica${r}${r}es", "Notificações")
    $c = $c.Replace("descri${r}${r}o", "descrição")
    $c = $c.Replace("Descri${r}${r}o", "Descrição")
    $c = $c.Replace("fun${r}${r}o", "função")
    $c = $c.Replace("Fun${r}${r}o", "Função")
    $c = $c.Replace("fun${r}${r}es", "funções")
    $c = $c.Replace("gera${r}${r}o", "geração")
    $c = $c.Replace("Gera${r}${r}o", "Geração")
    $c = $c.Replace("confirma${r}${r}o", "confirmação")
    $c = $c.Replace("visualiza${r}${r}o", "visualização")
    $c = $c.Replace("aprova${r}${r}o", "aprovação")
    $c = $c.Replace("compensa${r}${r}o", "compensação")
    $c = $c.Replace("Compensa${r}${r}o", "Compensação")
    $c = $c.Replace("remunera${r}${r}o", "remuneração")
    $c = $c.Replace("Remunera${r}${r}o", "Remuneração")
    $c = $c.Replace("dedu${r}${r}o", "dedução")
    $c = $c.Replace("Dedu${r}${r}o", "Dedução")
    $c = $c.Replace("dedu${r}${r}es", "deduções")
    $c = $c.Replace("Dedu${r}${r}es", "Deduções")
    $c = $c.Replace("promo${r}${r}o", "promoção")
    $c = $c.Replace("Promo${r}${r}o", "Promoção")
    $c = $c.Replace("posi${r}${r}o", "posição")
    $c = $c.Replace("Posi${r}${r}o", "Posição")
    $c = $c.Replace("documenta${r}${r}o", "documentação")
    $c = $c.Replace("atualiza${r}${r}o", "atualização")
    $c = $c.Replace("ALTERA${r}${r}ES", "ALTERAÇÕES")
    
    # Single replacement char patterns
    $c = $c.Replace("Gest${r}o", "Gestão")
    $c = $c.Replace("gest${r}o", "gestão")
    $c = $c.Replace("Funcion${r}rio", "Funcionário")
    $c = $c.Replace("funcion${r}rio", "funcionário")
    $c = $c.Replace("Usu${r}rio", "Usuário")
    $c = $c.Replace("usu${r}rio", "usuário")
    $c = $c.Replace("hor${r}rio", "horário")
    $c = $c.Replace("Hor${r}rio", "Horário")
    $c = $c.Replace("obrigat${r}rio", "obrigatório")
    $c = $c.Replace("Obrigat${r}rio", "Obrigatório")
    $c = $c.Replace("exclus${r}o", "exclusão")
    $c = $c.Replace("Exclus${r}o", "Exclusão")
    $c = $c.Replace("exclu${r}da", "excluída")
    $c = $c.Replace("exclu${r}do", "excluído")
    $c = $c.Replace("Relat${r}rio", "Relatório")
    $c = $c.Replace("relat${r}rio", "relatório")
    $c = $c.Replace("conex${r}o", "conexão")
    $c = $c.Replace("v${r}nculo", "vínculo")
    $c = $c.Replace("V${r}nculo", "Vínculo")
    $c = $c.Replace("c${r}lculo", "cálculo")
    $c = $c.Replace("C${r}lculo", "Cálculo")
    $c = $c.Replace("sal${r}rio", "salário")
    $c = $c.Replace("Sal${r}rio", "Salário")
    $c = $c.Replace("benef${r}cio", "benefício")
    $c = $c.Replace("Benef${r}cio", "Benefício")
    $c = $c.Replace("per${r}odo", "período")
    $c = $c.Replace("Per${r}odo", "Período")
    $c = $c.Replace("m${r}dulo", "módulo")
    $c = $c.Replace("M${r}dulo", "Módulo")
    $c = $c.Replace("n${r}mero", "número")
    $c = $c.Replace("N${r}mero", "Número")
    $c = $c.Replace("c${r}digo", "código")
    $c = $c.Replace("C${r}digo", "Código")
    $c = $c.Replace("${r}ltimo", "último")
    $c = $c.Replace("${r}ltima", "última")
    $c = $c.Replace("pr${r}ximo", "próximo")
    $c = $c.Replace("Pr${r}ximo", "Próximo")
    $c = $c.Replace("prov${r}vel", "provável")
    $c = $c.Replace("dispon${r}vel", "disponível")
    $c = $c.Replace("Dispon${r}vel", "Disponível")
    $c = $c.Replace("poss${r}vel", "possível")
    $c = $c.Replace("Poss${r}vel", "Possível")
    $c = $c.Replace("inv${r}lido", "inválido")
    $c = $c.Replace("Inv${r}lido", "Inválido")
    $c = $c.Replace("v${r}lido", "válido")
    $c = $c.Replace("V${r}lido", "Válido")
    $c = $c.Replace("Mar${r}o", "Março")
    $c = $c.Replace("mar${r}o", "março")
    $c = $c.Replace("in${r}cio", "início")
    $c = $c.Replace("In${r}cio", "Início")
    $c = $c.Replace("Sa${r}das", "Saídas")
    $c = $c.Replace("sa${r}das", "saídas")
    $c = $c.Replace("Sa${r}da", "Saída")
    $c = $c.Replace("sa${r}da", "saída")
    $c = $c.Replace("M${r}s", "Mês")
    $c = $c.Replace("m${r}s", "mês")
    $c = $c.Replace("HIST${r}RICO", "HISTÓRICO")
    $c = $c.Replace("hist${r}rico", "histórico")
    $c = $c.Replace("Hist${r}rico", "Histórico")
    $c = $c.Replace("${r}teis", "úteis")
    $c = $c.Replace("${r}til", "útil")
    $c = $c.Replace("f${r}rias", "férias")
    $c = $c.Replace("F${r}rias", "Férias")
    $c = $c.Replace("di${r}rio", "diário")
    $c = $c.Replace("Di${r}rio", "Diário")
    $c = $c.Replace("necess${r}rio", "necessário")
    $c = $c.Replace("Necess${r}rio", "Necessário")
    $c = $c.Replace("tempor${r}rio", "temporário")
    $c = $c.Replace("volunt${r}rio", "voluntário")
    $c = $c.Replace("anu${r}ncio", "anúncio")
    $c = $c.Replace("conte${r}do", "conteúdo")
    $c = $c.Replace("Conte${r}do", "Conteúdo")
    $c = $c.Replace("l${r}quido", "líquido")
    $c = $c.Replace("L${r}quido", "Líquido")
    $c = $c.Replace("refer${r}ncia", "referência")
    $c = $c.Replace("Refer${r}ncia", "Referência")
    $c = $c.Replace("frequ${r}ncia", "frequência")
    $c = $c.Replace("Frequ${r}ncia", "Frequência")
    $c = $c.Replace("urg${r}ncia", "urgência")
    $c = $c.Replace("emerg${r}ncia", "emergência")
    $c = $c.Replace("enviar${r}", "enviar")
    $c = $c.Replace("pr${r}prio", "próprio")
    $c = $c.Replace("${r}rea", "área")
    $c = $c.Replace("${r}ndice", "índice")
    
    # Context specific - "não" with spaces
    $c = $c.Replace(" n${r}o ", " não ")
    $c = $c.Replace("'N${r}o ", "'Não ")
    $c = $c.Replace("(n${r}o)", "(não)")
    $c = $c.Replace("(n${r}o ", "(não ")
    
    # Em dash
    $c = $c.Replace(" ${r} ", " — ")
    
    # Fix })); syntax patterns (fetch calls with extra paren)
    $c = [regex]::Replace($c, "(headers:\s*authHeaders\(\)\s*\r?\n\s*)\}\)\);", '${1}});')
    
    $after = ([regex]::Matches($c, [regex]::Escape([string]$r))).Count
    
    [System.IO.File]::WriteAllText($f, $c, $utf8NoBom)
    Write-Host "$relPath : $before -> $after remaining"
    
    if ($after -gt 0) {
        $leftover = [regex]::Matches($c, ".{0,20}$([regex]::Escape([string]$r)).{0,20}")
        foreach ($m in $leftover | Select-Object -First 10) {
            Write-Host "  REMAINING: [$($m.Value)]"
        }
    }
}

Write-Host "=== ENCODING FIX DONE ==="
