$file = "g:\Outros computadores\Meu laptop (2)\Zyntra\src\routes\compras.js"
$c = [IO.File]::ReadAllText($file, [Text.Encoding]::UTF8)
$original = $c

# Batch comment replacements
$c = $c.Replace('// ROTAS DO M??DULO DE COMPRAS', '// ROTAS DO MÓDULO DE COMPRAS')
$c = $c.Replace('// Valida????o de CNPJ', '// Validação de CNPJ')
$c = $c.Replace('// Valida????o dos d??gitos verificadores', '// Validação dos dígitos verificadores')
$c = $c.Replace('// Fun????o para criar notifica????o', '// Função para criar notificação')
$c = $c.Replace("console.error('Erro ao criar notifica????o:', error)", "console.error('Erro ao criar notificação:', error)")
$c = $c.Replace('// FUN????ES DE VALIDA????O E EXTRA????O DE CHAVE NF-e', '// FUNÇÕES DE VALIDAÇÃO E EXTRAÇÃO DE CHAVE NF-e')
$c = $c.Replace('// Validar chave de acesso NF-e (44 d??gitos + DV)', '// Validar chave de acesso NF-e (44 dígitos + DV)')
$c = $c.Replace('// Calcular d??gito verificador usando m??dulo 11', '// Calcular dígito verificador usando módulo 11')
$c = $c.Replace('// Fun????o helper para extrair valor', '// Função helper para extrair valor')
$c = $c.Replace('// Dados do destinat??rio', '// Dados do destinatário')
$c = $c.Replace("// Pedidos por status (??ltimos 30 dias)", "// Pedidos por status (últimos 30 dias)")
$c = $c.Replace("'Fornecedor n??o encontrado'", "'Fornecedor não encontrado'")
$c = $c.Replace('// Buscar ??ltimas avalia????es', '// Buscar últimas avaliações')
$c = $c.Replace('// Buscar ??ltimos pedidos', '// Buscar últimos pedidos')
$c = $c.Replace("'Raz??o social ?? obrigat??ria'", "'Razão social é obrigatória'")
$c = $c.Replace("'CNPJ ?? obrigat??rio'", "'CNPJ é obrigatório'")
$c = $c.Replace("'CNPJ inv??lido'", "'CNPJ inválido'")
$c = $c.Replace("'Telefone ?? obrigat??rio'", "'Telefone é obrigatório'")
$c = $c.Replace("'Email inv??lido'", "'Email inválido'")
$c = $c.Replace('// Verificar se CNPJ j?? existe', '// Verificar se CNPJ já existe')
$c = $c.Replace("'CNPJ j?? cadastrado'", "'CNPJ já cadastrado'")
$c = $c.Replace('// Gerar c??digo do fornecedor', '// Gerar código do fornecedor')
$c = $c.Replace("'Pedido n??o encontrado'", "'Pedido não encontrado'")
$c = $c.Replace('// Buscar workflow de aprova????es', '// Buscar workflow de aprovações')
$c = $c.Replace("'Fornecedor e itens s??o obrigat??rios'", "'Fornecedor e itens são obrigatórios'")
$c = $c.Replace('// Gerar n??mero do pedido', '// Gerar número do pedido')
$c = $c.Replace('// Verificar se precisa de aprova????o', '// Verificar se precisa de aprovação')
$c = $c.Replace('// Buscar aprovadores necess??rios', '// Buscar aprovadores necessários')
$c = $c.Replace('// Criar workflow de aprova????o', '// Criar workflow de aprovação')
$c = $c.Replace('// Criar notifica????o para aprovador', '// Criar notificação para aprovador')
$c = $c.Replace("'Pedido aguardando aprova????o'", "'Pedido aguardando aprovação'")
$c = $c.Replace("aguarda sua aprova????o.", "aguarda sua aprovação.")
$c = $c.Replace('// Buscar workflow pendente do usu??rio', '// Buscar workflow pendente do usuário')
$c = $c.Replace("'Voc?? n??o tem permiss??o para aprovar este pedido'", "'Você não tem permissão para aprovar este pedido'")
$c = $c.Replace('// Verificar se h?? mais aprova????es pendentes', '// Verificar se há mais aprovações pendentes')
$c = $c.Replace('// Todas as aprova????es conclu??das', '// Todas as aprovações concluídas')
$c = $c.Replace("'Erro ao processar aprova????o'", "'Erro ao processar aprovação'")
$c = $c.Replace('// ==================== COTA????ES ====================', '// ==================== COTAÇÕES ====================')
$c = $c.Replace('// Listar cota????es', '// Listar cotações')
$c = $c.Replace("logger.error('Erro ao listar cota????es:', error)", "logger.error('Erro ao listar cotações:', error)")
$c = $c.Replace("'Erro ao buscar cota????es'", "'Erro ao buscar cotações'")
$c = $c.Replace('// Criar cota????o', '// Criar cotação')
$c = $c.Replace('// Gerar n??mero da cota????o', '// Gerar número da cotação')
$c = $c.Replace('// Inserir cota????o', '// Inserir cotação')
$c = $c.Replace('// Aqui voc?? pode implementar envio de email para fornecedor', '// Aqui você pode implementar envio de email para fornecedor')
$c = $c.Replace("logger.info(``Cota????o criada: ", "logger.info(``Cotação criada: ")
$c = $c.Replace("logger.error('Erro ao criar cota????o:', error)", "logger.error('Erro ao criar cotação:', error)")
$c = $c.Replace("'Erro ao criar cota????o'", "'Erro ao criar cotação'")
$c = $c.Replace('// FLUXO: Cota????o', '// FLUXO: Cotação')
$c = $c.Replace('// 1. Buscar a cota????o', '// 1. Buscar a cotação')
$c = $c.Replace("'Cota????o n??o encontrada'", "'Cotação não encontrada'")
$c = $c.Replace('// 2. Buscar itens da cota????o (tabela pode n??o existir ainda)', '// 2. Buscar itens da cotação (tabela pode não existir ainda)')
$c = $c.Replace("// Tabela cotacoes_itens pode n??o existir - continuar sem itens", "// Tabela cotacoes_itens pode não existir - continuar sem itens")
$c = $c.Replace("console.warn('[COMPRAS] Tabela cotacoes_itens n??o encontrada, continuando sem itens')", "console.warn('[COMPRAS] Tabela cotacoes_itens não encontrada, continuando sem itens')")
$c = $c.Replace("'Fornecedor ?? obrigat??rio'", "'Fornecedor é obrigatório'")
$c = $c.Replace('// 6. Gerar n??mero do pedido de compra', '// 6. Gerar número do pedido de compra')
$c = $c.Replace('// Buscar pre??o da proposta (se houver) ou usar pre??o de refer??ncia', '// Buscar preço da proposta (se houver) ou usar preço de referência')
$c = $c.Replace("// Tabela pode n??o existir", "// Tabela pode não existir")
$c = $c.Replace("Pedido gerado a partir da cota????o", "Pedido gerado a partir da cotação")
$c = $c.Replace('// 10. Atualizar status da cota????o para aprovada', '// 10. Atualizar status da cotação para aprovada')
$c = $c.Replace('// 12. Log da a????o', '// 12. Log da ação')
$c = $c.Replace("logger.info(``Cota????o ", "logger.info(``Cotação ")
$c = $c.Replace("logger.error('Erro ao aprovar cota????o e gerar pedido:', error)", "logger.error('Erro ao aprovar cotação e gerar pedido:', error)")
$c = $c.Replace('// Buscar detalhes de uma cota????o espec??fica', '// Buscar detalhes de uma cotação específica')
$c = $c.Replace('// Buscar cota????o', '// Buscar cotação')
$c = $c.Replace("logger.error('Erro ao buscar cota????o:', error)", "logger.error('Erro ao buscar cotação:', error)")
$c = $c.Replace("'Erro ao buscar cota????o'", "'Erro ao buscar cotação'")
$c = $c.Replace('// Gerar n??mero do recebimento', '// Gerar número do recebimento')
$c = $c.Replace('// Atualizar status do recebimento se houver diverg??ncia', '// Atualizar status do recebimento se houver divergência')
$c = $c.Replace('// ==================== NOTIFICA????ES ====================', '// ==================== NOTIFICAÇÕES ====================')
$c = $c.Replace('// Listar notifica????es do usu??rio', '// Listar notificações do usuário')
$c = $c.Replace("logger.error('Erro ao listar notifica????es:', error)", "logger.error('Erro ao listar notificações:', error)")
$c = $c.Replace("'Erro ao buscar notifica????es'", "'Erro ao buscar notificações'")
$c = $c.Replace('// Marcar notifica????o como lida', '// Marcar notificação como lida')
$c = $c.Replace("logger.error('Erro ao marcar notifica????o:', error)", "logger.error('Erro ao marcar notificação:', error)")
$c = $c.Replace("'Erro ao marcar notifica????o'", "'Erro ao marcar notificação'")
$c = $c.Replace("// Validar formato da chave (44 d??gitos)", "// Validar formato da chave (44 dígitos)")
$c = $c.Replace("'Chave de acesso inv??lida. Deve conter 44 d??gitos.'", "'Chave de acesso inválida. Deve conter 44 dígitos.'")
$c = $c.Replace("// Validar d??gito verificador", "// Validar dígito verificador")
$c = $c.Replace("'Chave de acesso inv??lida. D??gito verificador incorreto.'", "'Chave de acesso inválida. Dígito verificador incorreto.'")
$c = $c.Replace('// Extrair informa????es da chave de acesso', '// Extrair informações da chave de acesso')
$c = $c.Replace("'NF-e n??o encontrada ou n??o autorizada'", "'NF-e não encontrada ou não autorizada'")
$c = $c.Replace("// Se falhou a consulta ao SEFAZ, retornar dados extra??dos da chave", "// Se falhou a consulta ao SEFAZ, retornar dados extraídos da chave")
$c = $c.Replace("'N??o foi poss??vel consultar o SEFAZ. Dados extra??dos da chave de acesso.'", "'Não foi possível consultar o SEFAZ. Dados extraídos da chave de acesso.'")
$c = $c.Replace("'Chave de acesso n??o informada'", "'Chave de acesso não informada'")
$c = $c.Replace("'D??gito verificador da chave ?? inv??lido'", "'Dígito verificador da chave é inválido'")
$c = $c.Replace('// ==================== RELAT??RIOS ====================', '// ==================== RELATÓRIOS ====================')
$c = $c.Replace('// Relat??rio de compras por per??odo', '// Relatório de compras por período')
$c = $c.Replace("logger.error('Erro ao gerar relat??rio:', error)", "logger.error('Erro ao gerar relatório:', error)")
$c = $c.Replace("'Erro ao gerar relat??rio'", "'Erro ao gerar relatório'")
$c = $c.Replace('// Relat??rio de top fornecedores', '// Relatório de top fornecedores')
$c = $c.Replace('// Recalcular m??dias do fornecedor', '// Recalcular médias do fornecedor')

# Check remaining ?? 
$remaining = ([regex]::Matches($c, '\?\?')).Count
Write-Host "Remaining ?? count: $remaining"

# Save if changes were made
if ($c -ne $original) {
    [IO.File]::WriteAllText($file, $c, [Text.Encoding]::UTF8)
    Write-Host "File saved successfully"
} else {
    Write-Host "No changes detected!"
}
