$enc = New-Object System.Text.UTF8Encoding($false)

# === FIX src/routes/compras.js ===
$f = "g:\Outros computadores\Meu laptop (2)\Zyntra\src\routes\compras.js"
$c = [IO.File]::ReadAllText($f, [Text.Encoding]::UTF8)
$before = ([regex]::Matches($c, '\?\?')).Count

$c = $c.Replace('FUN????ES DE VALIDA????O E EXTRA????O DE CHAVE NF-e', 'FUNÇÕES DE VALIDAÇÃO E EXTRAÇÃO DE CHAVE NF-e')
$c = $c.Replace('==================== COTA????ES ====================', '==================== COTAÇÕES ====================')
$c = $c.Replace('==================== NOTIFICA????ES ====================', '==================== NOTIFICAÇÕES ====================')
$c = $c.Replace('==================== RELAT??RIOS ====================', '==================== RELATÓRIOS ====================')
$c = $c.Replace('ROTAS DO M??DULO DE COMPRAS', 'ROTAS DO MÓDULO DE COMPRAS')
$c = $c.Replace('Valida????o de CNPJ', 'Validação de CNPJ')
$c = $c.Replace('Valida????o dos d??gitos verificadores', 'Validação dos dígitos verificadores')
$c = $c.Replace('Fun????o para criar notifica????o', 'Função para criar notificação')
$c = $c.Replace('Erro ao criar notifica????o:', 'Erro ao criar notificação:')
$c = $c.Replace('Validar chave de acesso NF-e (44 d??gitos + DV)', 'Validar chave de acesso NF-e (44 dígitos + DV)')
$c = $c.Replace('Calcular d??gito verificador usando m??dulo 11', 'Calcular dígito verificador usando módulo 11')
$c = $c.Replace('Fun????o helper para extrair valor', 'Função helper para extrair valor')
$c = $c.Replace('Dados do destinat??rio', 'Dados do destinatário')
$c = $c.Replace('Pedidos por status (??ltimos 30 dias)', 'Pedidos por status (últimos 30 dias)')
$c = $c.Replace('Buscar ??ltimas avalia????es', 'Buscar últimas avaliações')
$c = $c.Replace('Buscar ??ltimos pedidos', 'Buscar últimos pedidos')
$c = $c.Replace('Recalcular m??dias do fornecedor', 'Recalcular médias do fornecedor')
$c = $c.Replace('Buscar workflow de aprova????es', 'Buscar workflow de aprovações')
$c = $c.Replace('Gerar n??mero do pedido', 'Gerar número do pedido')
$c = $c.Replace('Verificar se precisa de aprova????o', 'Verificar se precisa de aprovação')
$c = $c.Replace('Buscar aprovadores necess??rios', 'Buscar aprovadores necessários')
$c = $c.Replace('Criar workflow de aprova????o', 'Criar workflow de aprovação')
$c = $c.Replace('Criar notifica????o para aprovador', 'Criar notificação para aprovador')
$c = $c.Replace('Pedido aguardando aprova????o', 'Pedido aguardando aprovação')
$c = $c.Replace('aguarda sua aprova????o.', 'aguarda sua aprovação.')
$c = $c.Replace('Buscar workflow pendente do usu??rio', 'Buscar workflow pendente do usuário')
$c = $c.Replace('Verificar se h?? mais aprova????es pendentes', 'Verificar se há mais aprovações pendentes')
$c = $c.Replace('Todas as aprova????es conclu??das', 'Todas as aprovações concluídas')
$c = $c.Replace('Erro ao processar aprova????o', 'Erro ao processar aprovação')
$c = $c.Replace('Listar cota????es', 'Listar cotações')
$c = $c.Replace('Erro ao listar cota????es:', 'Erro ao listar cotações:')
$c = $c.Replace('Erro ao buscar cota????es', 'Erro ao buscar cotações')
$c = $c.Replace('Criar cota????o', 'Criar cotação')
$c = $c.Replace('Gerar n??mero da cota????o', 'Gerar número da cotação')
$c = $c.Replace('Inserir cota????o', 'Inserir cotação')
$c = $c.Replace('Aqui voc?? pode implementar envio de email para fornecedor', 'Aqui você pode implementar envio de email para fornecedor')
$c = $c.Replace('Cota????o criada:', 'Cotação criada:')
$c = $c.Replace('Erro ao criar cota????o:', 'Erro ao criar cotação:')
$c = $c.Replace('Erro ao criar cota????o', 'Erro ao criar cotação')
$c = $c.Replace('FLUXO: Cota????o ??? Fornecedor ??? Pedido de Compra', 'FLUXO: Cotação → Fornecedor → Pedido de Compra')
$c = $c.Replace('1. Buscar a cota????o', '1. Buscar a cotação')
$c = $c.Replace('2. Buscar itens da cota????o (tabela pode n??o existir ainda)', '2. Buscar itens da cotação (tabela pode não existir ainda)')
$c = $c.Replace('Tabela cotacoes_itens pode n??o existir - continuar sem itens', 'Tabela cotacoes_itens pode não existir - continuar sem itens')
$c = $c.Replace('Tabela cotacoes_itens n??o encontrada, continuando sem itens', 'Tabela cotacoes_itens não encontrada, continuando sem itens')
$c = $c.Replace('6. Gerar n??mero do pedido de compra', '6. Gerar número do pedido de compra')
$c = $c.Replace('Buscar pre??o da proposta (se houver) ou usar pre??o de refer??ncia', 'Buscar preço da proposta (se houver) ou usar preço de referência')
$c = $c.Replace('Tabela pode n??o existir', 'Tabela pode não existir')
$c = $c.Replace('Pedido gerado a partir da cota????o', 'Pedido gerado a partir da cotação')
$c = $c.Replace('10. Atualizar status da cota????o para aprovada', '10. Atualizar status da cotação para aprovada')
$c = $c.Replace('12. Log da a????o', '12. Log da ação')
$c = $c.Replace('aprovada ??? Pedido', 'aprovada → Pedido')
$c = $c.Replace('Erro ao aprovar cota????o e gerar pedido:', 'Erro ao aprovar cotação e gerar pedido:')
$c = $c.Replace('Buscar detalhes de uma cota????o espec??fica', 'Buscar detalhes de uma cotação específica')
$c = $c.Replace('Buscar cota????o', 'Buscar cotação')
$c = $c.Replace('Erro ao buscar cota????o:', 'Erro ao buscar cotação:')
$c = $c.Replace('Erro ao buscar cota????o', 'Erro ao buscar cotação')
$c = $c.Replace('Gerar n??mero do recebimento', 'Gerar número do recebimento')
$c = $c.Replace('Atualizar status do recebimento se houver diverg??ncia', 'Atualizar status do recebimento se houver divergência')
$c = $c.Replace('Listar notifica????es do usu??rio', 'Listar notificações do usuário')
$c = $c.Replace('Erro ao listar notifica????es:', 'Erro ao listar notificações:')
$c = $c.Replace('Erro ao buscar notifica????es', 'Erro ao buscar notificações')
$c = $c.Replace('Marcar notifica????o como lida', 'Marcar notificação como lida')
$c = $c.Replace('Erro ao marcar notifica????o:', 'Erro ao marcar notificação:')
$c = $c.Replace('Erro ao marcar notifica????o', 'Erro ao marcar notificação')
$c = $c.Replace('Validar formato da chave (44 d??gitos)', 'Validar formato da chave (44 dígitos)')
$c = $c.Replace('Chave de acesso inv??lida. Deve conter 44 d??gitos.', 'Chave de acesso inválida. Deve conter 44 dígitos.')
$c = $c.Replace('Validar d??gito verificador', 'Validar dígito verificador')
$c = $c.Replace('Chave de acesso inv??lida. D??gito verificador incorreto.', 'Chave de acesso inválida. Dígito verificador incorreto.')
$c = $c.Replace('Extrair informa????es da chave de acesso', 'Extrair informações da chave de acesso')
$c = $c.Replace('NF-e n??o encontrada ou n??o autorizada', 'NF-e não encontrada ou não autorizada')
$c = $c.Replace('retornar dados extra??dos da chave', 'retornar dados extraídos da chave')
$c = $c.Replace('N??o foi poss??vel consultar o SEFAZ. Dados extra??dos da chave de acesso.', 'Não foi possível consultar o SEFAZ. Dados extraídos da chave de acesso.')
$c = $c.Replace('D??gito verificador da chave ?? inv??lido', 'Dígito verificador da chave é inválido')
$c = $c.Replace('Relat??rio de compras por per??odo', 'Relatório de compras por período')
$c = $c.Replace('Erro ao gerar relat??rio:', 'Erro ao gerar relatório:')
$c = $c.Replace('Erro ao gerar relat??rio', 'Erro ao gerar relatório')
$c = $c.Replace('Relat??rio de top fornecedores', 'Relatório de top fornecedores')
# User-visible strings
$c = $c.Replace("Raz??o social ?? obrigat??ria", "Razão social é obrigatória")
$c = $c.Replace("CNPJ ?? obrigat??rio", "CNPJ é obrigatório")
$c = $c.Replace("CNPJ inv??lido", "CNPJ inválido")
$c = $c.Replace("Telefone ?? obrigat??rio", "Telefone é obrigatório")
$c = $c.Replace("Email inv??lido", "Email inválido")
$c = $c.Replace("CNPJ j?? existe", "CNPJ já existe")
$c = $c.Replace("CNPJ j?? cadastrado", "CNPJ já cadastrado")
$c = $c.Replace("Gerar c??digo do fornecedor", "Gerar código do fornecedor")
$c = $c.Replace("Fornecedor n??o encontrado", "Fornecedor não encontrado")
$c = $c.Replace("Pedido n??o encontrado", "Pedido não encontrado")
$c = $c.Replace("Fornecedor e itens s??o obrigat??rios", "Fornecedor e itens são obrigatórios")
$c = $c.Replace("Voc?? n??o tem permiss??o para aprovar este pedido", "Você não tem permissão para aprovar este pedido")
$c = $c.Replace("Cota????o n??o encontrada", "Cotação não encontrada")
$c = $c.Replace("Fornecedor ?? obrigat??rio", "Fornecedor é obrigatório")
$c = $c.Replace("Chave de acesso n??o informada", "Chave de acesso não informada")
$c = $c.Replace("Chave de acesso inv??lida. Deve conter 44 d??gitos.", "Chave de acesso inválida. Deve conter 44 dígitos.")
$c = $c.Replace("D??gito verificador da chave ?? inv??lido", "Dígito verificador da chave é inválido")

[IO.File]::WriteAllText($f, $c, $enc)
$after = ([regex]::Matches($c, '\?\?')).Count
Write-Host "compras.js OK: antes=$before restantes=$after"

# === FIX routes/compras-routes.js ===
$f2 = "g:\Outros computadores\Meu laptop (2)\Zyntra\routes\compras-routes.js"
$c2 = [IO.File]::ReadAllText($f2, [Text.Encoding]::UTF8)
$before2 = ([regex]::Matches($c2, '\?\?')).Count

$c2 = $c2.Replace('relat??rios, centros de custo)', 'relatórios, centros de custo)')
$c2 = $c2.Replace('est??o em compras-extended.js', 'estão em compras-extended.js')
$c2 = $c2.Replace('RELAT??RIOS DE COMPRAS', 'RELATÓRIOS DE COMPRAS')
$c2 = $c2.Replace('Relat??rio de gastos por per??odo', 'Relatório de gastos por período')
$c2 = $c2.Replace('Estat??sticas de Recebimento', 'Estatísticas de Recebimento')
$c2 = $c2.Replace("estat??sticas de recebimento:", "estatísticas de recebimento:")
$c2 = $c2.Replace("Produ????o", "Produção")

[IO.File]::WriteAllText($f2, $c2, $enc)
$after2 = ([regex]::Matches($c2, '\?\?')).Count
Write-Host "compras-routes.js OK: antes=$before2 restantes=$after2"
